allowBuilds:
  esbuild: true
packageImportMethod: copy
shellEmulator: true
overrides:
  "@codemirror/state": 6.7.6
  "@codemirror/view": 6.43.13
minimumReleaseAgeExclude:
  - "@types/node@24.19.2"
  - obsidian@1.14.4
